version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true
clone_depth: 1
image: Visual Studio 2017
cache: c:\tools\vcpkg\installed\

install:
  - vcpkg install wxwidgets

before_build:
  - cmake -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
  verbosity: minimal
