orbs:
  git: guitarrapc/git-shallow-clone@0.2.0
version: 2.1
jobs:
  build:
    docker:
      - image: debian:buster
    working_directory: ~/repo
    steps:
      - git-shallow-clone
      - run: apt-get update -y
      - run: apt-get install -y --no-install-recommends libgtk2.0-dev pkg-config build-essential git cmake libssh-dev libwxbase3.0-dev libsqlite3-dev libwxsqlite3-3.0-dev
      - run: mkdir build-release
      - run: cd build-release && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
      - run: cd build-release && make -j$(nproc)
